---
title: "Reproducible Research Project 1"
author: "Andrew Roberts"
date: "March 2, 2016"
output: html_document
---

##Data

This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.

The data can be downloaded [here](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip).

First, we load the packages we need to complete the assignment.  We will use the `dplyr` package.
```{R load, echo=TRUE, results="hide"}
library(dplyr)
```


We run the following code to produce a data frame named `act1` using the `activity.csv` data file. We convert the act1 data frame to the tbl class, which we can manipulate using dplyr. We examine the structure of the tbl using the str function.

```{R readdata, echo=TRUE}
act1 <- read.csv("activity.csv")
act <- tbl_df(act1)
str(act)
```

##What is the mean total number of steps taken per day?
###Calculate the total number of steps taken per day
We use the `group_by` function to group the data by date.  Then we remove NAs and summarize total steps by day using the `summarize` and `sum` functions.
```{R total_steps, echo=TRUE}
total <- group_by(act,date) %>% 
        na.omit() %>% 
        summarize(total_steps=sum(steps))
head(total)
```

###Make a histogram of the total number of steps taken each day
We use the `hist` function to create a histogram of the total steps taken each day.
```{R histogram, echo=TRUE}
hist(total$total_steps,
     main="Total Daily Steps",
     col="blue",
     xlab="Number of Steps")
```

###Calculate and report the mean and median of the total number of steps taken per day
We use the `mean` and `median` functions to calculate the mean and median of the total number of steps taken per day.

####Mean
```{R mean, echo=TRUE}
o_mean <- mean(total$total_steps)
o_mean
```

####Median
```{R median, echo=TRUE}
o_med <- median(total$total_steps)
o_med
```

##What is the average daily pattern?
###Make a time series plot of the 5-minute interval and the average number of steps taken, averaged across all days

First, we group the data by interval.  Then we calculate the average steps by interval across all days.
```{R interval, echo=TRUE}
int <- group_by(act,interval) %>% 
        na.omit() %>% 
        summarize(avg_steps = mean(steps))
head(int)
```

Then we use the `plot` function to create a time series plot of the data.
```{R time_series, echo=TRUE}
plot(int$interval,int$avg_steps,
     type="l",
     xlab="Interval",
     ylab="Number of Steps",
     main="Average Number of Steps per Day by Interval")
```

###Find the 5-minute interval that, on average across all days in the dataset, contains the maximum number of steps
We can use the `which.max` function to subset the data and determine which interval has the maximum number of steps on average across all days.
```{R max_steps, echo=TRUE}
int[which.max(int$avg_steps),1]
```

##Imputing missing values
###Calculate and report the total number of missing values in the dataset
We use the `sum` and `complete.cases` functions to calculate the total number of rows with missing data.
```{R total_NA, echo=TRUE}
sum(!complete.cases(act))
```

###Fill in all of the missing values in the dataset.
We will use the average value for the interval to replace any missing values.

###Create a new dataset that is equal to the original dataset but with the missing data filled in.
We will create a new dataset, `act_imp`, which will contain imputed values for any missing data.  We will first join the `int` dataset containing the average steps by interval with the `act` dataset.  Then if a value is missing, we will use `avg_steps` instead.  We then drop `avg_steps` from the dataset. 
```{R impute, echo=TRUE}
act_imp <- left_join(act,int,by="interval") %>% 
        mutate(steps=ifelse(is.na(steps),avg_steps,steps)) %>% 
        select(-avg_steps)
head(act_imp)
```

###Make a histogram of the total number of steps taken each day and calculate the mean and median total number of steps taken per day.
First we need to recalculate the total number of steps per day using our new imputed dataset.  We use the same method we used above.
```{R total_steps_imp, echo=TRUE}
total_imp <- group_by(act_imp,date) %>% 
        summarize(total_steps=sum(steps))
head(total_imp)
```

We then create a histogram of the data.
```{R histogram_imp, echo=TRUE}
hist(total_imp$total_steps,
     main="Total Steps Each Day",
     col="blue",
     xlab="Number of Steps")
```

We calculate the mean and the median total number of steps taken per day using the imputed data set.

####Mean using imputed data
```{R imp_mean,echo=TRUE}
imp_mean <- mean(total_imp$total_steps)
imp_mean
```
####Median using imputed data
```{R imp_med,echo=TRUE}
imp_med <- median(total_imp$total_steps)
imp_med
```

###What is the impact of imputing missing data on the estimates of the total daily number of steps?

We can calulate the difference in the mean and median between our non-imputed dataset and our imputed dataset.

####Difference in Mean
```{R differ_mean, echo=TRUE}
o_mean - imp_mean
```
We can see that the mean is identical using imputed data.  This makes sense, as we used a mean value for each interval to impute the missing values.

####Difference in Median
```{R differ_med, echo=TRUE}
o_med - imp_med
```
We can see that the median differs slightly when calculated using imputed data compared to non-imputed data.  The median for the imputed data is slightly higher.

##Are there differences in activity patterns between weekdays and weekends?

### Create a new factor variable in the dataset indicating whether a given date is a weekday or weekend day.
We use convert the `date` variable to a POSIXlt variable using the `as.Date` function, then apply the `weekdays` function to determine the day of the week.  We then use the `ifelse` function to assign either "weekend" or "weekday" in the `weekday` factor variable.
```{R weekday,echo=TRUE}
act_dow <- mutate(act_imp,dow=weekdays(as.Date(date,"%Y-%m-%d"))) %>% 
        mutate(weekday=as.factor(ifelse(dow %in% c("Saturday","Sunday"),"weekend","weekday")))
head(act_dow)
```

###Make a panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday days or weekend days.
First, we need to create our summary dataset using our new data with the `weekday` variable, using the same method as above.  We will create one dataset for weekend data:
```{R wkend_int, echo=TRUE}
int_wkend <- filter(act_dow,weekday=="weekend") %>% 
        group_by(interval) %>% 
        na.omit() %>% 
        summarize(avg_steps = mean(steps))
head(int_wkend)
```

And another dataset for weekday data:
```{R wkday_int, echo=TRUE}
int_wkday <- filter(act_dow,weekday=="weekday") %>% 
        group_by(interval) %>% 
        na.omit() %>% 
        summarize(avg_steps = mean(steps))
head(int_wkday)
```

Next, we will create our plot.  First, we will use the `par` function to set the `mfrow` attribute so we can have multiple panels.  Then we will create our two plots.
```{R plot_dow, echo=TRUE, fig.height=8}
par(mfrow=c(2,1))
with(int_wkday,
     plot(interval,avg_steps,
          main="Average Number of Steps Taken by Interval Across All Weekdays",
          xlab="Interval",
          ylab="Number of Steps",
          type="l"))
with(int_wkend,
     plot(interval,avg_steps,
          main="Average Number of Steps Taken by Interval Across All Weekend Days",
          xlab="Interval",
          ylab="Number of Steps",
          type="l"))
```